# Generated by Django 4.1 on 2022-08-10 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 10, 19, 27, 22, 819330)),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 10, 19, 29, 22, 819330)),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 15, 19, 27, 22, 820328)),
        ),
    ]
